name: build
on: [push]
jobs:
  build:
    runs-on: macos-14
    steps:
      - run: |
          brew install boost
          git clone --recursive --branch Release_2024_03_6 https://github.com/rdkit/rdkit.git
          cd rdkit
          cmake -S . -B build \
            -DRDK_BUILD_COORDGEN_SUPPORT=OFF \
            -DRDK_BUILD_MAEPARSER_SUPPORT=OFF \
            -DRDK_BUILD_PYTHON_WRAPPERS=OFF \
            -DRDK_USE_BOOST_IOSTREAMS=OFF \
            -DRDK_USE_BOOST_SERIALIZATION=OFF \
            -DRDK_USE_BOOST_STACKTRACE=OFF
          cmake --build build
